# ----------------------------------------------------------
# Settings
# ----------------------------------------------------------

shell /opt/homebrew/bin/fish
hide_window_decorations no
enabled_layouts tall
window_margin_width 5
active_border_color #00ff00
inactive_border_color #cccccc

# ----------------------------------------------------------
# Keymaps
# ----------------------------------------------------------

map ctrl+p new_window
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up

listen_on unix:@mykitty
